datafile: data/S20by100_peoplegroup.pkl
project_name: ''
log_wandb: True
sf_init: 1
init_file: ''
learner: adam
learning_rate: 1/1000
weight_decay: 0
epochs: 1000
stopping_step: 100
valid_metric: ''
valid_metric_bigger: True
eval_batch_size: 2
device: cuda
eval_device: cuda
checkpoint_dir: tmp/small_ppl/
save_dir: tmp/small_ppl/
model_file: gd_opt
model_activation: hardtanh
model: Popt
trainer: MOOTrainer
eval_type: 2
eval_step: 1
loss_decimal_place: 4
m: 20
n: 100
k: 10
seed: 42
reproducibility: True
sf_temp: 10
gd_accum: 1
envy_weight: 1
inferiority_weight: 1
utility_weight: 1
prob_weight: 1
batch_size: 128
u_sample_size: 400
i_sample_size: 1000
sample_mode: both
stopping: ''
dynamic_scale: True
warmup: 50
scale_max: 50